server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


appDescription: "Stock"
appVersion: "1.0.0"